FROM node:18.12.1-alpine As build
LABEL org.opencontainers.image.source="https://github.com/luismij/cumbi"

# Install nodemon globally
RUN npm install -g nodemon

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . /usr/src/app

# Use nodemon to run the application with live reloading
CMD [ "nodemon", "/usr/src/app/app.js" ]
