name: Deploy Images to GHCR

on:
  push:
    branches:
      - stage

jobs:
  push-store-image:
    name: Build and push image to registry
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Image'
        run: |
          REPO_NAME=${{ github.repository }}
          IMAGE_URL="ghcr.io/${REPO_NAME,,}:staging"
          docker build . --tag ${IMAGE_URL}
          docker push ${IMAGE_URL}
  redeploy:
    name: Redeploy
    runs-on: staging-self-hosted
    needs: [push-store-image]
    steps:
      - name: Pull Latest Images
        run: cd /home/ubuntu && bash redeploy.sh